### ISSUE TITLE
Link to Slack channel on homepage is broken

### ISSUE THREAD

**Issue by Teebusch** [FelixHenninger/lab.js#124]
### What would you like or expect to see?

The link to the Slack channel on the [lab.js home page](https://lab.js.org/) needs to be fixed.

### What is currently happening?

Clicking on the link in "You'll always find friendly people in our Slack channel. We're happy to help!" leads to 
https://slackin-nmbrcrnchrs.herokuapp.com/
which shows an error message

![image](https://user-images.githubusercontent.com/3391092/117325860-6ac94b80-ae91-11eb-99db-1e70dc6bf50e.png)

**Comment by FelixHenninger** [comment]
Hi @Teebusch, and many thanks spotting this -- that's some eagle-eyed bugspotting! 👍

I recently updated the code and created a new application on Heroku, but forgot to update the link. Should be fixed as of 273820f868af0848119b884489168e6ed02d766f !

Kind regards, and thanks again -Felix

**Comment by Teebusch** [comment]
You're welcome! Thanks for building lab.js! :)

I just realized that the link in the docs points to the same (broken) Heroku app:  😱https://labjs.readthedocs.io/en/latest/meta/support.html

**Comment by FelixHenninger** [comment]
Oh dear, you're absolutely right, heartfelt thanks! I did what I should have done the first time, and found even more instances of the outdated link 😅. Hopefully d2f82f48a0cfa93d1a2b8f749d97ccca17b95e01 gets us closer to fixing them.

**Comment by mcfarla9** [comment]
Note that this issue has come up again -- see #200, #208, and now #209.

**Comment by IsabelleBarrett** [comment]
Hey, just want to flag this issue is still present as of today. It is seemingly correctly redirecting to [https://slackin-numbercrunchers.herokuapp.com/](https://slackin-numbercrunchers.herokuapp.com/) but still getting the herokuapp error page. My understanding from more recent issue logs is that there are/were plans to move the community to another platform, but the slack is also still linked on the home page
